import type {AggregatedPoint,AppSettings,DisplayMode,ESGCategory,RiskInput,RiskItem,RiskLevel,RiskThresholds} from './types';
export const defaultThresholds:RiskThresholds={lowMax:4,mediumMax:9,highMax:16};export const defaultSettings:AppSettings={thresholds:defaultThresholds,chart:{displayMode:'aggregate',minBubbleSize:14,maxBubbleSize:44}};
export const riskLevelLabels:Record<RiskLevel,string>={LOW:'低风险',MEDIUM:'中风险',HIGH:'高风险',CRITICAL:'极高风险'};export const categoryLabels:Record<ESGCategory,string>={E:'环境',S:'社会',G:'治理'};
export const riskColors:Record<RiskLevel,string>={LOW:'#16a34a',MEDIUM:'#f59e0b',HIGH:'#ef4444',CRITICAL:'#991b1b'};export const riskBgColors:Record<RiskLevel,string>={LOW:'#dcfce7',MEDIUM:'#fef9c3',HIGH:'#fee2e2',CRITICAL:'#fecaca'};export const esgColors:Record<ESGCategory,string>={E:'#16a34a',S:'#2563eb',G:'#f97316'};
export function calculateRiskScore(L:number,I:number){return L*I}export function calculateWeight(FM:number,IM:number){return (FM+IM)/2}export function calculateRiskLevel(R:number,t:RiskThresholds):RiskLevel{return R<=t.lowMax?'LOW':R<=t.mediumMax?'MEDIUM':R<=t.highMax?'HIGH':'CRITICAL'}
export function calculateBubbleSize(W:number,s:AppSettings['chart']){const min=Math.max(4,s.minBubbleSize),max=Math.max(min+1,s.maxBubbleSize);return min+(max-min)*(Math.sqrt(W)-1)/(Math.sqrt(5)-1)}
export function normalizeCategory(v:string):ESGCategory|null{const x=String(v||'').trim().toUpperCase();if(['E','环境'].includes(x))return'E';if(['S','社会'].includes(x))return'S';if(['G','治理'].includes(x))return'G';return null}
export function hydrateRisk(input:RiskInput,thresholds:RiskThresholds,id=input instanceof Object&&'id'in input?String((input as any).id):crypto.randomUUID()):RiskItem{const R=calculateRiskScore(input.L,input.I),W=calculateWeight(input.FM,input.IM);return{...input,id,R,W,riskLevel:calculateRiskLevel(R,thresholds)}}
export function validateScore(v:number){return Number.isInteger(v)&&v>=1&&v<=5}export function validateRiskInput(r:Partial<RiskInput>){const e:string[]=[];if(!r.riskName?.trim())e.push('风险名称不能为空');if(!r.esgTopic?.trim())e.push('ESG议题不能为空');if(!r.esgCategory)e.push('ESG分类必须为E/S/G或环境/社会/治理');(['L','I','FM','IM'] as const).forEach(k=>{if(!validateScore(Number(r[k])))e.push(`${k}值必须为1–5整数`)});return e}
export function aggregatePoints(risks:RiskItem[],getX:(r:RiskItem)=>number,getY:(r:RiskItem)=>number):AggregatedPoint[]{const m=new Map<string,RiskItem[]>();risks.forEach(r=>{const k=`${getX(r)}-${getY(r)}`;m.set(k,[...(m.get(k)||[]),r])});return[...m.entries()].map(([key,rs])=>{const levels={LOW:0,MEDIUM:0,HIGH:0,CRITICAL:0} as Record<RiskLevel,number>;rs.forEach(r=>levels[r.riskLevel]++);return{key,x:getX(rs[0]),y:getY(rs[0]),risks:rs,count:rs.length,maxR:Math.max(...rs.map(r=>r.R)),avgW:+(rs.reduce((a,r)=>a+r.W,0)/rs.length).toFixed(2),maxW:Math.max(...rs.map(r=>r.W)),levelDistribution:levels}})}
function stableOffset(id:string,index:number,total:number){let h=0;for(const c of id)h=(h*31+c.charCodeAt(0))>>>0;const angle=(h%360)*Math.PI/180;const ring=total<=1?0:(0.05+((index%3)+1)*0.03);return{dx:Math.cos(angle)*Math.min(ring,.14),dy:Math.sin(angle)*Math.min(ring,.14)}}
export function jitteredPoints(risks:RiskItem[],getX:(r:RiskItem)=>number,getY:(r:RiskItem)=>number){const groups=aggregatePoints(risks,getX,getY);return groups.flatMap(g=>g.risks.map((r,i)=>{const o=stableOffset(r.id,i,g.count);return{risk:r,displayX:g.x+o.dx,displayY:g.y+o.dy,trueX:g.x,trueY:g.y}}))}
export function chartPoints(risks:RiskItem[],mode:DisplayMode,getX:(r:RiskItem)=>number,getY:(r:RiskItem)=>number){return mode==='aggregate'?aggregatePoints(risks,getX,getY):jitteredPoints(risks,getX,getY)}
